### ISSUE TITLE
 gyp ERR! on RasPian trying to: npm install node-sqlite3

### ISSUE THREAD

**Issue by devbox** [mapbox/node-sqlite3#500] opened 2015-08-29 15:13 UTC
Hey,
got the following ERR when i tried to "npm install node-sqlite3" on my Raspberry Pi 2 with Raspbian OS on it:
...
node_sqlite3.target.mk:104: recipe for target 'Release/obj.target/node_sqlite3/src/nodejs/Sqlite3Client.o' failed
make: *** [Release/obj.target/node_sqlite3/src/nodejs/Sqlite3Client.o] Error 1
make: Leaving directory '/node_modules/node-sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.6-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/node-sqlite3
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 4.1.6-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-sqlite3" "--unsafe-per"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! node-sqlite3@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sqlite3@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sqlite3
npm ERR! There is likely additional logging output above.

tried several things, also the unrecommended, --unsafe-pre and execute as root.
Any idea?

**Comment by ErisDS** [comment] 2015-11-01 14:36
closing as a duplicate of #501

**Closed by ErisDS** 2015-11-01 14:36 UTC
