### ISSUE TITLE
issue installing ghost blog, erroring on sqlite3 install

### ISSUE THREAD

**Issue by jpascualtango** [mapbox/node-sqlite3#435] opened 2015-04-03 18:52 UTC
hi,

i'm trying to install ghost blog on centos6 box. it seems to break on the sqlite3 portion of the install. if you can help, that would be great. if i run just the command to install sqlite3 (npm install sqlite3 --build-from-source) here's the error messages i get:
> sqlite3@3.0.5 install /var/www/ghost/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

make: Entering directory `/var/www/ghost/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080701/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080701/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
make: g++: Command not found
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 127
make: Leaving directory `/var/www/ghost/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-431.29.2.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=3.0.5" "--major=3" "--patch=5" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/var/www/ghost/node_modules/sqlite3/lib/binding/node-v11-linux-x64" "--module=/var/www/ghost/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node" "--remote_path=./sqlite3/v3.0.5/" "--package_name=node-v11-linux-x64.tar.gz" "--staged_tarball=build/stage/sqlite3/v3.0.5/node-v11-linux-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-v11-linux-x64.tar.gz"
gyp ERR! cwd /var/www/ghost/node_modules/sqlite3
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.5 --major=3 --patch=5 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/var/www/ghost/node_modules/sqlite3/lib/binding/node-v11-linux-x64 --module=/var/www/ghost/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node --remote_path=./sqlite3/v3.0.5/ --package_name=node-v11-linux-x64.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.5/node-v11-linux-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-v11-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/ghost/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:71:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 2.6.32-431.29.2.el6.x86_64
node-pre-gyp ERR! command "node" "/var/www/ghost/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/ghost/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.38
node-pre-gyp ERR! node-pre-gyp -v v0.6.2
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.5 --major=3 --patch=5 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/var/www/ghost/node_modules/sqlite3/lib/binding/node-v11-linux-x64 --module=/var/www/ghost/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node --remote_path=./sqlite3/v3.0.5/ --package_name=node-v11-linux-x64.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.5/node-v11-linux-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-v11-linux-x64.tar.gz' (1)
npm ERR! Linux 2.6.32-431.29.2.el6.x86_64
npm ERR! argv "node" "/usr/bin/npm" "install" "sqlite3" "--build-from-source"
npm ERR! node v0.10.38
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/ghost/npm-debug.log

thanks!
jeremy

**Comment by springmeyer** [comment] 2015-05-04 20:56
the problem is likely #444. That is triggering a fallback to a source compile and that is failing because you don't have a compiler (e.g. g++) installed. So, this will work in the upcoming v3.0.6 release now that #444 is merged.

**Closed by springmeyer** 2015-05-04 20:56 UTC
