### ISSUE TITLE
Compatibility list for node versions and node-sqlite3 versions

### ISSUE THREAD

**Issue by benderTheCrime** [mapbox/node-sqlite3#460] opened 2015-06-12 14:44 UTC
```javascript
module.js:318
    throw err;
          ^
Error: Cannot find module '**node_modules/sqlite3/lib/binding/node-v43-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.Module._load (module.js:258:25)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (**node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:410:26)
    at Module._extensions..js (module.js:428:10)
    at Object.require.extensions.(anonymous function) [as .js] (**node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:171:7)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
```

Is there a list of versions/compatibility of node and this package? I am using nvm and no version of iojs/node I set prevents this error.

**Comment by springmeyer** [comment] 2015-06-12 15:14
See the https://github.com/mapbox/node-sqlite3/blob/master/.travis.yml#L16-L19 for a sense of what we test on. Can you provide the terminal output from `npm install` so we can see what caused the install to fail?

**Comment by benderTheCrime** [comment] 2015-06-12 15:19
The install worked fine, or at least if it did not errors were suppressed. It's looking for `node-v43-darwin-x64`. In that location, I see a directory called `node-v44-darwin-x64`.

**Comment by springmeyer** [comment] 2015-06-12 15:34
hmm sounds like you may have conflicting node versions somehow. can you describe how you installed node and what version?

**Comment by benderTheCrime** [comment] 2015-06-12 16:45
Here's what I've tried: locally, I use [nvm](https://github.com/creationix/nvm) to manage my node versions. This package was working as expected until yesterday. I dropped my npm packages and did a fresh install with version ^3.0.5 specified in my `package.json` https://github.com/benderTheCrime/angie. After what looked like a successful install, starting my package failed. I run my package in a linked directory with `npm link`. To try and remedy since then I have deleted all of my packages, made sure that
node 0.12.x was installed in both my package directory and the linked directory and reinstalled. When that failed, I repeated the process with iojs-v2.2.1.

**Comment by benderTheCrime** [comment] 2015-06-13 16:46
Ok, I did not want to remedy this issue in this fashion because I had other packages which depended on my nvm states, but it was the surefire way to resolve this issue. Perhaps this will help other users in the future? 

If you are using nvm and you run into the issue above, do the following:
```bash
# Remove your nvm environments
rm -rf ~/.nvm ~/.npm ~/.bower

# Use system nvm
nvm use system
```

From there, I would recommend deleting your node_modules and seeing if a fresh install works before trying to add any nvm environments.

**Comment by talkingtab** [comment] 2015-06-13 17:32
I'm not sure if this is relevant, but I ran into problems because I did not understand nvm and npm interaction.

If you use nvm to install multiple instances of node/io.js then each instance will have its own repository of global installs. For example if you:

`npm install colors -g`

and then use nvm to switch to a different version of node or io.js, then colors will not be available, it must be reinstalled for each engine version.

In addition if you install a package locally that is dependent on a particular version of node/io.js and then use nvm to switch to a different version you may also run into problems.

**Comment by benderTheCrime** [comment] 2015-06-13 17:59
Yes, that is very relevant, however, in this context not the case of my problem (a good comparison for the way that nvm works is rvm and the explanation for how rvm works is way better).

In this case, I made sure that there were no globally installed versions of the package by using each version of nvm I had installed locally and running an uninstall (including `nvm use system`) and then doing a global find on the package name to clear out any binaries. Then making sure that I only installed packages locally).

Ultimately, I do not know what the root cause of this problem is for certain, but I did diagnose global installs in each of the installed nvm versions I was using.

**Comment by lhecker** [comment] 2015-06-25 14:13
@benderTheCrime Wouldn't this all be fixed by uploading a v44 ABI build for node-pre-gyp?

Previously I had installed an older io.js which ran just fine (I don't remember which version it was though). After upgrading io.js it fails the same way as described in #449. Obviously it's due to the old io.js (somewhere around 1.6) version providing the v43 ABI, but the new io.js (2.3.1) providing the v44 ABI, due to which io.js either isn't able to find (as it's the case here) or load the binary.

Nowadays it just fails to download https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.8/node-v44-win32-x64.tar.gz and thus aborts `npm install` for me.

**Comment by benderTheCrime** [comment] 2015-06-25 14:40
This would be a good solution if it was for my own use! But it is for an npm package. I am relying on the install to install the proper node-pre-gyp based on what version of node/iojs they are running.

**Comment by benderTheCrime** [comment] 2015-06-25 14:41
Can the package install both by default?

**Comment by springmeyer** [comment] 2015-06-25 17:23
@benderTheCrime To recap: I think your system has seriously messed up/ conflicting installs and it all boils down to that: in the sense is the only way to avoid it is to clean up your installs - which you did. Unless there is some subtle bug in node-pre-gyp where it is picking up the wrong version when it should not. But I'd need a reproducible testcase to demonstrate that.

> @springmeyer Can the package install both by default?
@benderTheCrime - not by default, but you can certainly install binaries for multiple node versions if you like. This would allow you to switch between different node versions without re-installing (because they would both be placed in the correct versioned directory). So yes, if I'm understanding your question correctly the way you would do this is `npm install --target=0.10.33` <-- that would install the right ABI for node v0.10.x for example. See https://github.com/mapbox/node-pre-gyp#options and let me know if you need more docs.

> @benderTheCrime Wouldn't this all be fixed by uploading a v44 ABI build for node-pre-gyp?

@lhecker - this issue I think is specific to a mac os x system with duplicated/conflicting node versions. The issue you are calling out is a true missing package that I was unaware of. Ticketed at https://github.com/mapbox/node-sqlite3/issues/469. Thanks.

Closing this now. Please re-open new issues and clarify any problems you see that I might be missing :)

**Closed by springmeyer** 2015-06-25 17:23 UTC
