### ISSUE TITLE
build failure - 3.0.9 will not install from npm

### ISSUE THREAD

**Issue by Pomax** [mapbox/node-sqlite3#483] opened 2015-07-21 20:06 UTC
the current version 3.0.9 on npm is failing its build and cannot be installed. Manually installing 3.0.8 works, but having the build fixed is definitely preferable =D

**Comment by Stono** [comment] 2015-07-22 10:58
+1, this has just broken 3 of my build pipelines!

**Comment by gregtampa** [comment] 2015-07-24 20:17
can yall fix your build before publishing to npm grr

**Comment by springmeyer** [comment] 2015-08-06 15:45
Can someone provide more details of what the error was that you saw? And please confirm if you are still seeing it?

**Comment by springmeyer** [comment] 2015-08-06 15:55
Going to presume you are hitting #484. Please open a new issue with details if the problem is different.

**Comment by Pomax** [comment] 2015-08-06 17:17
Better to delete those comments and reopen this: look at the README.md: this is not "us", this is "you": your CI is failing to build your release.

![screenshot 71](https://cloud.githubusercontent.com/assets/177243/9118290/548ce006-3c24-11e5-9973-aaf62cc16cca.png)

**Comment by springmeyer** [comment] 2015-08-06 17:56
@Pomax I'm happy to fix the problem if you can share what exact error you are hitting. The failing status badges currently are unrelated, temporary, and expected.

**Comment by Pomax** [comment] 2015-08-06 19:36
I'm on a windows machine, for which building things from source is the most insanely broken process in the history of Node.js, so I rely on sqlite3's super handy precompiled binaries, and I can't get those because npm can't find them.

![screenshot 72](https://cloud.githubusercontent.com/assets/177243/9121537/af040bb4-3c37-11e5-820f-bbff038ad4f9.png)

**Comment by springmeyer** [comment] 2015-08-06 19:57
> I can't get those because npm can't find them and tries to fall back to C++ compilation.

Okay, thanks for clarifying. Can you share what node version you are using? Also please run `npm install sqlite3 --loglevel=verbose` and post the terminal output. Please post the text not a screenshot.

**Comment by Pomax** [comment] 2015-08-06 21:46
node v0.12.7 with npm 2.11.3. Verbose install log:
```
j:\temp\_>npm install sqlite3 --loglevel=verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   'sqlite3',
npm verb cli   '--loglevel=verbose' ]
npm info using npm@2.11.3
npm info using node@v0.12.7
npm verb install initial load of j:\temp\_\package.json
npm verb readDependencies loading dependencies from j:\temp\_\package.json
npm verb cache add spec sqlite3
npm verb addNamed "*" is a valid semver range for sqlite3
npm verb addNameRange registry:https://registry.npmjs.org/sqlite3 not in flight; fetching
npm verb request uri https://registry.npmjs.org/sqlite3
npm verb request no auth needed
npm info attempt registry request try #1 at 2:45:36 PM
npm verb request id 132682852c650e93
npm verb etag "83O88BZL25H0PYO8ZU92WJ0H8"
npm http request GET https://registry.npmjs.org/sqlite3
npm http 304 https://registry.npmjs.org/sqlite3
npm verb etag https://registry.npmjs.org/sqlite3 from cache
npm verb get saving sqlite3 to C:\Users\Mike\AppData\Roaming\npm-cache\registry.npmjs.org\sqlite3\.cache.json
npm verb addNamed "3.0.10" is a plain semver version for sqlite3
npm verb afterAdd C:\Users\Mike\AppData\Roaming\npm-cache\sqlite3\3.0.10\package\package.json not in flight; writing
npm verb afterAdd C:\Users\Mike\AppData\Roaming\npm-cache\sqlite3\3.0.10\package\package.json written
npm info install sqlite3@3.0.10 into j:\temp\_
npm info installOne sqlite3@3.0.10
npm verb installOne of sqlite3 to j:\temp\_ not in flight; installing
npm verb lock using C:\Users\Mike\AppData\Roaming\npm-cache\_locks\sqlite3-3e288d50eb7ab2de.lock for j:\temp\_\node_modules\sqlite3
npm verb unbuild node_modules\sqlite3
npm verb gentlyRm don't care about contents; nuking j:\temp\_\node_modules\sqlite3
npm verb tar unpack C:\Users\Mike\AppData\Roaming\npm-cache\sqlite3\3.0.10\package.tgz
npm verb tar unpacking to j:\temp\_\node_modules\sqlite3
npm verb gentlyRm don't care about contents; nuking j:\temp\_\node_modules\sqlite3
npm verb write writing to j:\temp\_\node_modules\sqlite3\package.json
npm info preinstall sqlite3@3.0.10
npm verb readDependencies loading dependencies from j:\temp\_\node_modules\sqlite3\package.json
npm verb readDependencies loading dependencies from j:\temp\_\node_modules\sqlite3\package.json
npm verb targetResolver reading package data from j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\package.json
npm info package.json node-pre-gyp@0.6.9 license should be a valid SPDX license expression
npm verb cache add spec nan@~1.8.4
npm verb addNamed ">=1.8.4 <1.9.0" is a valid semver range for nan
npm verb addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
npm verb request uri https://registry.npmjs.org/nan
npm verb request no auth needed
npm info attempt registry request try #1 at 2:45:41 PM
npm verb etag "9TM5STV36BTUZ5A79JIW8E2V2"
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm verb etag https://registry.npmjs.org/nan from cache
npm verb get saving nan to C:\Users\Mike\AppData\Roaming\npm-cache\registry.npmjs.org\nan\.cache.json
npm verb addNamed "1.8.4" is a plain semver version for nan
npm verb afterAdd C:\Users\Mike\AppData\Roaming\npm-cache\nan\1.8.4\package\package.json not in flight; writing
npm verb afterAdd C:\Users\Mike\AppData\Roaming\npm-cache\nan\1.8.4\package\package.json written
npm verb installMany node-pre-gyp@0.6.9 was bundled with sqlite3@3.0.10
npm info install nan@1.8.4 into j:\temp\_\node_modules\sqlite3
npm info installOne nan@1.8.4
npm verb installOne of nan to j:\temp\_\node_modules\sqlite3 not in flight; installing
npm verb lock using C:\Users\Mike\AppData\Roaming\npm-cache\_locks\nan-599214079933e1d1.lock for j:\temp\_\node_modules\sqlite3\node_modules\nan
npm verb unbuild node_modules\sqlite3\node_modules\nan
npm verb gentlyRm don't care about contents; nuking j:\temp\_\node_modules\sqlite3\node_modules\nan
npm verb tar unpack C:\Users\Mike\AppData\Roaming\npm-cache\nan\1.8.4\package.tgz
npm verb tar unpacking to j:\temp\_\node_modules\sqlite3\node_modules\nan
npm verb gentlyRm don't care about contents; nuking j:\temp\_\node_modules\sqlite3\node_modules\nan
npm verb write writing to j:\temp\_\node_modules\sqlite3\node_modules\nan\package.json
npm info preinstall nan@1.8.4
npm verb readDependencies loading dependencies from j:\temp\_\node_modules\sqlite3\node_modules\nan\package.json
npm verb readDependencies loading dependencies from j:\temp\_\node_modules\sqlite3\node_modules\nan\package.json
npm verb about to build j:\temp\_\node_modules\sqlite3\node_modules\nan
npm info build j:\temp\_\node_modules\sqlite3\node_modules\nan
npm info linkStuff nan@1.8.4
npm verb linkBins nan@1.8.4
npm verb linkMans nan@1.8.4
npm verb rebuildBundles nan@1.8.4
npm info install nan@1.8.4
npm info postinstall nan@1.8.4
npm verb unlock done using C:\Users\Mike\AppData\Roaming\npm-cache\_locks\nan-599214079933e1d1.lock for j:\temp\_\node_modules\sqlite3\node_modules\nan
npm verb about to build j:\temp\_\node_modules\sqlite3
npm info build j:\temp\_\node_modules\sqlite3
npm info linkStuff sqlite3@3.0.10
npm verb linkBins sqlite3@3.0.10
npm verb linkMans sqlite3@3.0.10
npm verb rebuildBundles sqlite3@3.0.10
npm verb rebuildBundles [ 'nan', 'node-pre-gyp' ]
npm verb rebuild bundle j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp
npm info build j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp
npm info preinstall node-pre-gyp@0.6.9
npm info linkStuff node-pre-gyp@0.6.9
npm verb linkBins node-pre-gyp@0.6.9
npm verb link bins [ { 'node-pre-gyp': './bin/node-pre-gyp' },
npm verb link bins   'j:\\temp\\_\\node_modules\\sqlite3\\node_modules\\.bin',
npm verb link bins   false ]
npm verb linkMans node-pre-gyp@0.6.9
npm verb rebuildBundles node-pre-gyp@0.6.9
npm verb rebuildBundles [ 'mkdirp',
npm verb rebuildBundles   'nopt',
npm verb rebuildBundles   'npmlog',
npm verb rebuildBundles   'rc',
npm verb rebuildBundles   'request',
npm verb rebuildBundles   'rimraf',
npm verb rebuildBundles   'semver',
npm verb rebuildBundles   'tar',
npm verb rebuildBundles   'tar-pack' ]
npm verb rebuild bundle j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\mkdirp
npm info build j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\mkdirp
npm info preinstall mkdirp@0.5.1
npm info linkStuff mkdirp@0.5.1
npm verb linkBins mkdirp@0.5.1
npm verb link bins [ { mkdirp: 'bin/cmd.js' },
npm verb link bins   'j:\\temp\\_\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\node_modules\\.bin',
npm verb link bins   false ]
npm verb linkMans mkdirp@0.5.1
npm verb rebuildBundles mkdirp@0.5.1
npm verb rebuildBundles [ 'minimist' ]
npm info install mkdirp@0.5.1
npm info postinstall mkdirp@0.5.1
npm verb rebuild bundle j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\nopt
npm info build j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\nopt
npm info preinstall nopt@3.0.3
npm info linkStuff nopt@3.0.3
npm verb linkBins nopt@3.0.3
npm verb link bins [ { nopt: './bin/nopt.js' },
npm verb link bins   'j:\\temp\\_\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\node_modules\\.bin',
npm verb link bins   false ]
npm verb linkMans nopt@3.0.3
npm verb rebuildBundles nopt@3.0.3
npm verb rebuildBundles [ 'abbrev' ]
npm info install nopt@3.0.3
npm info postinstall nopt@3.0.3
npm verb rebuild bundle j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\npmlog
npm info build j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\npmlog
npm info preinstall npmlog@1.2.1
npm info linkStuff npmlog@1.2.1
npm verb linkBins npmlog@1.2.1
npm verb linkMans npmlog@1.2.1
npm verb rebuildBundles npmlog@1.2.1
npm verb rebuildBundles [ 'ansi', 'are-we-there-yet', 'gauge' ]
npm info install npmlog@1.2.1
npm info postinstall npmlog@1.2.1
npm verb rebuild bundle j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\rc
npm info build j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\rc
npm info preinstall rc@1.1.0
npm info linkStuff rc@1.1.0
npm verb linkBins rc@1.1.0
npm verb link bins [ { rc: './index.js' },
npm verb link bins   'j:\\temp\\_\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\node_modules\\.bin',
npm verb link bins   false ]
npm verb linkMans rc@1.1.0
npm verb rebuildBundles rc@1.1.0
npm verb rebuildBundles [ 'deep-extend', 'ini', 'minimist', 'strip-json-comments' ]
npm info install rc@1.1.0
npm info postinstall rc@1.1.0
npm verb rebuild bundle j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\request
npm info build j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\request
npm info preinstall request@2.60.0
npm info linkStuff request@2.60.0
npm verb linkBins request@2.60.0
npm verb linkMans request@2.60.0
npm verb rebuildBundles request@2.60.0
npm verb rebuildBundles [ 'aws-sign2',
npm verb rebuildBundles   'bl',
npm verb rebuildBundles   'caseless',
npm verb rebuildBundles   'combined-stream',
npm verb rebuildBundles   'extend',
npm verb rebuildBundles   'forever-agent',
npm verb rebuildBundles   'form-data',
npm verb rebuildBundles   'har-validator',
npm verb rebuildBundles   'hawk',
npm verb rebuildBundles   'http-signature',
npm verb rebuildBundles   'isstream',
npm verb rebuildBundles   'json-stringify-safe',
npm verb rebuildBundles   'mime-types',
npm verb rebuildBundles   'node-uuid',
npm verb rebuildBundles   'oauth-sign',
npm verb rebuildBundles   'qs',
npm verb rebuildBundles   'stringstream',
npm verb rebuildBundles   'tough-cookie',
npm verb rebuildBundles   'tunnel-agent' ]
npm info install request@2.60.0
npm info postinstall request@2.60.0
npm verb rebuild bundle j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\rimraf
npm info build j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\rimraf
npm info preinstall rimraf@2.4.2
npm info linkStuff rimraf@2.4.2
npm verb linkBins rimraf@2.4.2
npm verb link bins [ { rimraf: './bin.js' },
npm verb link bins   'j:\\temp\\_\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\node_modules\\.bin',
npm verb link bins   false ]
npm verb linkMans rimraf@2.4.2
npm verb rebuildBundles rimraf@2.4.2
npm verb rebuildBundles [ 'glob' ]
npm info install rimraf@2.4.2
npm info postinstall rimraf@2.4.2
npm verb rebuild bundle j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\semver
npm info build j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\semver
npm info preinstall semver@5.0.1
npm info linkStuff semver@5.0.1
npm verb linkBins semver@5.0.1
npm verb link bins [ { semver: './bin/semver' },
npm verb link bins   'j:\\temp\\_\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\node_modules\\.bin',
npm verb link bins   false ]
npm verb linkMans semver@5.0.1
npm verb rebuildBundles semver@5.0.1
npm info install semver@5.0.1
npm info postinstall semver@5.0.1
npm verb rebuild bundle j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\tar
npm info build j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\tar
npm info preinstall tar@2.1.1
npm info linkStuff tar@2.1.1
npm verb linkBins tar@2.1.1
npm verb linkMans tar@2.1.1
npm verb rebuildBundles tar@2.1.1
npm verb rebuildBundles [ 'block-stream', 'fstream', 'inherits' ]
npm info install tar@2.1.1
npm info postinstall tar@2.1.1
npm verb rebuild bundle j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\tar-pack
npm info build j:\temp\_\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\tar-pack
npm info preinstall tar-pack@2.0.0
npm info linkStuff tar-pack@2.0.0
npm verb linkBins tar-pack@2.0.0
npm verb linkMans tar-pack@2.0.0
npm verb rebuildBundles tar-pack@2.0.0
npm verb rebuildBundles [ 'debug',
npm verb rebuildBundles   'fstream',
npm verb rebuildBundles   'fstream-ignore',
npm verb rebuildBundles   'graceful-fs',
npm verb rebuildBundles   'once',
npm verb rebuildBundles   'readable-stream',
npm verb rebuildBundles   'rimraf',
npm verb rebuildBundles   'tar',
npm verb rebuildBundles   'uid-number' ]
npm info install tar-pack@2.0.0
npm info postinstall tar-pack@2.0.0
npm info install node-pre-gyp@0.6.9
npm info postinstall node-pre-gyp@0.6.9
npm info install sqlite3@3.0.10

> sqlite3@3.0.10 install j:\temp\_\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'node',
node-pre-gyp verb cli   'j:\\temp\\_\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.9
node-pre-gyp info using node@0.12.7 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "j:\temp\_\node_modules\sqlite3\lib\binding\node-v14-win32-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.10/node-v14-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.10/node-v14-win32-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.10/node-v14-win32-x64.tar.gz (falling back to source compile with node-gyp)
node-pre-gyp verb command build [ 'rebuild' ]
```

**Comment by springmeyer** [comment] 2015-08-06 23:32
Confirmed a publishing bug that impacted windows. I think I've fixed it. @Pomax - can you try installing again now?

**Comment by Pomax** [comment] 2015-08-07 01:02
confirmed, it no longer tries to do a full build from source. Awesome!

**Comment by ErisDS** [comment] 2015-11-01 13:42
Closing as this was resolved 😊

**Closed by ErisDS** 2015-11-01 13:42 UTC
Labels: install
