### ISSUE TITLE
Fails to build for node-webkit using nw-gyp on mac

### ISSUE THREAD

**Issue by edhedges** [mapbox/node-sqlite3#380] opened 2014-12-29 04:18 UTC
I've previously gotten this to work on my windows machine using the following:

```npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=ia32 --target="0.10.5"```

On my mac I have a bit of a different set up and I'm unable to get things to build.

I used the following:

```npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target="0.11.5"```

Here are the relevant logs:

```
1055 info install tar-pack@2.0.0
1056 info postinstall tar-pack@2.0.0
1057 info install node-pre-gyp@0.6.1
1058 info postinstall node-pre-gyp@0.6.1
1059 info install sqlite3@3.0.4
1060 verbose unsafe-perm in lifecycle false
1061 info sqlite3@3.0.4 Failed to exec install script
1062 verbose unlock done using /Users/ed/.npm/_locks/sqlite3-7baed64d8652bf89.lock for /Users/ed/EdsDev/pensieve/node_modules/sqlite3
1063 verbose stack Error: sqlite3@3.0.4 install: `node-pre-gyp install --fallback-to-build`
1063 verbose stack Exit status 1
1063 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
1063 verbose stack     at EventEmitter.emit (events.js:98:17)
1063 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
1063 verbose stack     at ChildProcess.emit (events.js:98:17)
1063 verbose stack     at maybeClose (child_process.js:766:16)
1063 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
1064 verbose pkgid sqlite3@3.0.4
1065 verbose cwd /Users/ed/EdsDev/pensieve
1066 error Darwin 13.1.0
1067 error argv "node" "/usr/local/bin/npm" "install" "sqlite3" "--build-from-source" "--runtime=node-webkit" "--target_arch=x64" "--target=0.11.5"
1068 error node v0.10.35
1069 error npm  v2.1.16
1070 error code ELIFECYCLE
1071 error sqlite3@3.0.4 install: `node-pre-gyp install --fallback-to-build`
1071 error Exit status 1
1072 error Failed at the sqlite3@3.0.4 install script 'node-pre-gyp install --fallback-to-build'.
1072 error This is most likely a problem with the sqlite3 package,
1072 error not with npm itself.
1072 error Tell the author that this fails on your system:
1072 error     node-pre-gyp install --fallback-to-build
1072 error You can get their info via:
1072 error     npm owner ls sqlite3
1072 error There is likely additional logging output above.
1073 verbose exit [ 1, true ]
1074 verbose unbuild node_modules/sqlite3
1075 info preuninstall sqlite3@3.0.4
```

Any ideas? I couldn't find anything searching around so I figured I'd try here.

**Comment by lforge** [comment] 2015-02-13 21:59
I am having the same issue.  Is there any update on this?  Thanks.

**Comment by springmeyer** [comment] 2015-02-13 22:48
node-webkit 0.11.x is not supported. Stick to 0.10.x for now. Closing as duplicate of https://github.com/mapbox/node-sqlite3/issues/404

**Closed by springmeyer** 2015-02-13 22:48 UTC
