### ISSUE TITLE
glibc 2.14 dependency 

### ISSUE THREAD

**Issue by seebees** [mapbox/node-sqlite3#484] opened 2015-07-22 23:51 UTC
In 3.0.9 #244 is now an issue again.  Trying to use node-sqlite3 on CentOs 6 and I have a less happy day.

It appears to have been fixed by #444.  Can this be re-applied?  Or was this done on purpose?

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by .../node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../index.js:4:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by springmeyer** [comment] 2015-08-06 15:53
Yes, this worked in v3.0.8, broke in v3.0.9, and will work again in v3.0.10. The problem is we have no good way to test and prevent regression currently.

refs https://github.com/mapbox/node-sqlite3/issues/459#issuecomment-128416060

**Comment by springmeyer** [comment] 2015-08-06 16:00
should be fixed by https://github.com/mapbox/node-sqlite3/commit/4955b79f04509196a15c360e612f9c0c393c3609

**Closed by springmeyer** 2015-08-06 16:00 UTC

**Comment by seebees** [comment] 2015-08-06 22:34
I feel your pain.  Tests ftw.  Wish I could help.  Thanks for taking care of it.
