### ISSUE TITLE
Module not found: Error: Can't resolve 'node-pre-gyp' 

### ISSUE THREAD

**Issue by RobertRajcool** [mapbox/node-sqlite3#909] opened 2017-11-15 15:50 UTC
ERROR in sqlite3/lib/sqlite3.js
Module not found: Error: Can't resolve 'node-pre-gyp' in

**Comment by RobertRajcool** [comment] 2017-11-15 15:50
Can help me!!!

**Comment by benschool** [comment] 2017-11-15 17:00
npm install node-pre-gyp

**Comment by RobertRajcool** [comment] 2017-11-15 17:42
after install this package node-pre-gyp
getting lot of error

WARNING in ./~/node-pre-gyp/lib/util/compile.js
Module not found: Error: Can't resolve 'npm' in '/home/robert/electron/angular2-electron/node_modules/node-pre-gyp/lib/util'
 @ ./~/node-pre-gyp/lib/util/compile.js 39:27-49
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

WARNING in ./~/node-gyp/lib/Find-VS2017.cs
Module parse failed: /home/robert/electron/angular2-electron/node_modules/node-gyp/lib/Find-VS2017.cs Unexpected token (7:6)
You may need an appropriate loader to handle this file type.
| // Usage:
| // powershell -ExecutionPolicy Unrestricted -Version "2.0" -Command "&{Add-Type -Path Find-VS2017.cs; [VisualStudioConfiguration.Main]::Query()}"
| using System;
| using System.Text;
| using System.Runtime.InteropServices;
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/node-pre-gyp/lib/util/compile.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

WARNING in ./~/sqlite3/lib/sqlite3.js
4:14-35 Critical dependency: the request of a dependency is an expression

WARNING in ./~/node-pre-gyp/lib/pre-binding.js
19:22-48 Critical dependency: the request of a dependency is an expression

WARNING in ./~/node-pre-gyp/lib/util/versioning.js
16:20-67 Critical dependency: the request of a dependency is an expression

ERROR in ./~/node-pre-gyp/lib/info.js
Module not found: Error: Can't resolve 'aws-sdk' in '/home/robert/electron/angular2-electron/node_modules/node-pre-gyp/lib'
 @ ./~/node-pre-gyp/lib/info.js 14:14-32
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-pre-gyp/lib/publish.js
Module not found: Error: Can't resolve 'aws-sdk' in '/home/robert/electron/angular2-electron/node_modules/node-pre-gyp/lib'
 @ ./~/node-pre-gyp/lib/publish.js 17:14-32
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-pre-gyp/lib/unpublish.js
Module not found: Error: Can't resolve 'aws-sdk' in '/home/robert/electron/angular2-electron/node_modules/node-pre-gyp/lib'
 @ ./~/node-pre-gyp/lib/unpublish.js 15:14-32
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-pre-gyp/lib/testbinary.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/node-pre-gyp/lib'
 @ ./~/node-pre-gyp/lib/testbinary.js 10:9-33
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-pre-gyp/lib/util/compile.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/node-pre-gyp/lib/util'
 @ ./~/node-pre-gyp/lib/util/compile.js 9:9-33
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/detect-libc/lib/detect-libc.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/detect-libc/lib'
 @ ./~/detect-libc/lib/detect-libc.js 4:16-40
 @ ./~/node-pre-gyp/lib/util/versioning.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-gyp/lib/node-gyp.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/node-gyp.js 16:20-44
 @ ./~/node-pre-gyp/lib/util/compile.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/osenv/osenv.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/osenv'
 @ ./~/osenv/osenv.js 3:11-35
 @ ./~/nopt/lib/nopt.js
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-gyp/lib/node-gyp.js
Module not found: Error: Can't resolve '../package' in '/home/robert/electron/angular2-electron/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/node-gyp.js 67:16-37
 @ ./~/node-pre-gyp/lib/util/compile.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-gyp/lib/build.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/build.js 14:11-35
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/node-pre-gyp/lib/util/compile.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-gyp/lib/configure.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/configure.js 19:9-33
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/node-pre-gyp/lib/util/compile.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-gyp/lib/find-vs2017.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/find-vs2017.js 2:15-39
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/node-pre-gyp/lib/util/compile.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/uid-number/uid-number.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/uid-number'
 @ ./~/uid-number/uid-number.js 9:20-44
 @ ./~/tar-pack/index.js
 @ ./~/node-pre-gyp/lib/package.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

**Comment by wmertens** [comment] 2017-12-26 20:42
Do you still have this issue? This seems to be a Node configuration issue. Unless you can show how to reproduce this on a recent Node install, I propose that you close this issue

**Comment by kadupenido** [comment] 2018-01-08 21:44
I'm having the same problem trying to build a version
I also tried to install the node-pre-gyp package and more bugs were created


I'm using...

```
@angular/cli: 1.4.4
node: 7.10.1
os: win32 x64
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/compiler-cli: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/cli: 1.4.4
typescript: 2.3.4
```


```
Error: ./node_modules/sqlite3/lib/sqlite3.js
Module not found: Error: Can't resolve 'node-pre-gyp' in 'D:\_projetos\Mobile\trunk\App\node_modules\sqlite3\lib'
resolve 'node-pre-gyp' in 'D:\_projetos\Mobile\trunk\App\node_modules\sqlite3\lib'
  Parsed request is a module
  using description file: D:\_projetos\Mobile\trunk\App\node_modules\sqlite3\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\_projetos\Mobile\trunk\App\node_modules\sqlite3\package.json (relative path: ./lib)
    resolve as module
      looking for modules in D:\_projetos\Mobile\trunk\App\node_modules
        using description file: D:\_projetos\Mobile\trunk\App\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\_projetos\Mobile\trunk\App\package.json (relative path: ./node_modules)
          using description file: D:\_projetos\Mobile\trunk\App\package.json (relative path: ./node_modules/node-pre-gyp)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\_projetos\Mobile\trunk\App\node_modules\node-pre-gyp doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\_projetos\Mobile\trunk\App\node_modules\node-pre-gyp.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\_projetos\Mobile\trunk\App\node_modules\node-pre-gyp.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\_projetos\Mobile\trunk\App\node_modules\node-pre-gyp.json doesn't exist
            as directory
              D:\_projetos\Mobile\trunk\App\node_modules\node-pre-gyp doesn't exist
[D:\_projetos\Mobile\trunk\App\node_modules\node-pre-gyp]
[D:\_projetos\Mobile\trunk\App\node_modules\node-pre-gyp.ts]
[D:\_projetos\Mobile\trunk\App\node_modules\node-pre-gyp.js]
[D:\_projetos\Mobile\trunk\App\node_modules\node-pre-gyp.json]
[D:\_projetos\Mobile\trunk\App\node_modules\node-pre-gyp]
 @ ./node_modules/sqlite3/lib/sqlite3.js 1:13-36
 @ ./node_modules/typeorm/platform/PlatformTools.js
 @ ./node_modules/typeorm/entity-manager/MongoEntityManager.js
 @ ./node_modules/typeorm/index.js
 @ ./src/areas/projeto/domain/peca-item-projeto.ts
 @ ./src/areas/projeto/domain/index.ts
 @ ./src/providers/database-provider.ts
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts
    at new BuildError (D:\_projetos\Mobile\trunk\App\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (D:\_projetos\Mobile\trunk\App\node_modules\@ionic\app-scripts\dist\webpack.js:123:28)
    at emitRecords.err (D:\_projetos\Mobile\trunk\App\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (D:\_projetos\Mobile\trunk\App\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (D:\_projetos\Mobile\trunk\App\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (D:\_projetos\Mobile\trunk\App\node_modules\webpack\lib\Compiler.js:368:12)
    at next (D:\_projetos\Mobile\trunk\App\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (D:\_projetos\Mobile\trunk\App\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (D:\_projetos\Mobile\trunk\App\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (D:\_projetos\Mobile\trunk\App\node_modules\webpack\lib\Compiler.js:365:9)


```

**Comment by gitsana** [comment] 2018-01-26 20:25
I have this issue too. @RobertRajcool @wmertens any proposed solutions?

**Comment by wmertens** [comment] 2018-01-29 06:09
Seeing how you're trying to build on windows, did you install the toolset?

npm install --global --production windows-build-tools

**Comment by wmertens** [comment] 2018-02-01 12:34
I saw this `child_process` error elsewhere: it was due to the dev using a module in a webpack build that imported `child_process` somewhere. Browsers cannot use node APIs, so be careful to not include it anywhere.

**Comment by marswong** [comment] 2018-02-03 09:25
I had failed to build `sqlite3` for thousand times no matter how, for the `aws-sdk` relys on `child_process` so every time you `require('sqlite3')` on client side it could not be resolved.

Luckily, I found an awesome module can work like a charm on both client or server side - [sql.js](https://github.com/kripken/sql.js) created by the `emscripten`'s author.

If you are still in troubles with integrating `electron` and `sqlite`, you should have a try :)

**Comment by wmertens** [comment] 2018-02-03 11:06
You could alias child_process to a module that fakes it all. I wonder how
you can use aws-sdk on the client side though, if it relies on
child_process.

**Comment by barbalex** [comment] 2018-04-04 16:05
I have same problem. On Windows. Using electron. Exact error is:
```
./node_modules/sqlite3/node_modules/node-pre-gyp/lib/info.js
Module not found: Can't resolve 'aws-sdk' in 'C:\Users\alexa\kapla4\node_modules\sqlite3\node_modules\node-pre-gyp\lib'
```

`npm install --global --production windows-build-tools` is installed.

`child_process` is only used node-side in my electron project to start electron after create-react-app has started:

```js
const net = require('net')
const port = process.env.PORT ? process.env.PORT - 100 : 5000

process.env.ELECTRON_START_URL = `http://localhost:${port}`

const client = new net.Socket()

let startedElectron = false
const tryConnection = () =>
  client.connect({ port: port }, () => {
    client.end()
    if (!startedElectron) {
      console.log('starting electron')
      startedElectron = true
      const exec = require('child_process').exec
      exec('yarn run electron')
    }
  })

tryConnection()

client.on('error', error => {
  setTimeout(tryConnection, 1000)
})
```

The exact same project structure and configuration works flawlessly in another project created yesterday that does not use native modules i.e. sqlite3.

**Comment by barbalex** [comment] 2018-10-09 20:42
@axelkennedal I ended up not using create-react-app but instead [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) which solves the problem by using another package.json file - somehow...

**Comment by dstrawsb** [comment] 2018-10-17 04:04
> @barbalex I'm also getting same error message with Sequelize, irritating, i'm not using sqlLite3.

**Comment by mnmpeterson** [comment] 2019-02-01 22:16
I'm getting this problem with fsevents on a Mac.  Cannot find a solution.

**Comment by wmertens** [comment] 2019-02-02 07:00
@mnmpeterson try deleting node_modules, package-lock.json and/or yarn.lock, and install again

**Comment by askogrand** [comment] 2019-02-26 14:17
For what its worth — I've run into the same problem. Deleting node_modules and lock files doesnt help, nor does adding node-pre-gyp globally. I think I too will use the other [boilerplate](https://github.com/chentsulin/electron-react-boilerplate)

**Comment by WilliamC07** [comment] 2019-08-11 03:40
If you are using electron, I used the package "electron-rebuild" to fix this.
I ran the command "./node_modules/.bin/electron-rebuild  -f -w sqlite3"
It seems to break if I have multiple require('sqlite').

**Comment by mayurssoni2456** [comment] 2019-10-09 08:10
hi all, I am facing the same issue on Mac. Is anyone able to solve this problem?
I tried almost all solution available. Still no luck.



> For what its worth — I've run into the same problem. Deleting node_modules and lock files doesnt help, nor does adding node-pre-gyp globally. I think I too will use the other [boilerplate](https://github.com/chentsulin/electron-react-boilerplate)

Hey, we were able to fix this issue after using boilerplate code and SQLite? curious to know :)

**Comment by feng005211** [comment] 2019-11-22 02:52
This problem bothered me for three days, and now it's finally solved
Reference resources
https://github.com/mapbox/node-sqlite3/issues/1029#issuecomment-414116796

My solution:
```
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath,
      libraryTarget: 'commonjs2'
  },
  externals: {
      sqlite3: 'sqlite3'
  }
```
important code
      libraryTarget: 'commonjs2'
      sqlite3: 'sqlite3'

**If you solve this problem because of my solution, please share it with those who need help. And use this link。 :)**

**Comment by Jclyoung** [comment] 2020-01-15 19:42
This was happening to me because I was pointing to the wrong dependency

in my case, it was bcrypt that was causing the issue


error received when using :
**const bcrypt = require('bcrypt')**

error fixed when using : 
**const bcrypt = require('bcryptjs')**

**Closed** 2020-03-13 21:07 UTC

**Comment by xtfer** [comment] 2020-04-23 23:38
Not sure why this was closed. It's still very much a problem.

**Comment by rajtussspacetech** [comment] 2020-09-13 19:10
Thanks @Jclyoung

**Comment by firien** [comment] 2020-11-23 21:44
```
resolve: {
  alias: {
    [path.join(__dirname, 'node_modules/sqlite3/lib/sqlite3-binding.js')]: path.join(__dirname, 'path/to/local/sqlite3-binding.js')
  }
}
```

path/to/local/sqlite3-binding.js:

**Comment by firien** [comment] 2020-11-23 22:02
for webpack users trying to bundle sqlite3; there may be a better way to do this, but you can override new `sqlite3-binding.js` with `resolve` and point to a different file.

```js
resolve: {
  alias: {
    [path.join(__dirname, 'node_modules/sqlite3/lib/sqlite3-binding.js')]: path.join(__dirname, 'path/to/local/sqlite3-binding.js')
  }
}
```
path/to/local/sqlite3-binding.js:
```js
var binding = require('bindings')('node_sqlite3');
module.exports = exports = binding;
```

this approach requires the bindings package.
> npm install bindings --save-dev

note: you will have copy the `node_sqlite3.node` file to specified [directories](https://github.com/TooTallNate/node-bindings#nice-error-output)

**Comment by dotgreg** [comment] 2021-07-15 21:33
July 2021, still having that issue with webpack + sqlite3 on linux
I managed however to solve it by modifying my webpack config file as that comment suggests
https://github.com/mapbox/node-sqlite3/issues/1029#issuecomment-414116796

**Comment by karlhorky** [comment] 2023-02-27 11:37
> This was happening to me because I was pointing to the wrong dependency
> 
> in my case, it was bcrypt that was causing the issue
> 
> error received when using : **const bcrypt = require('bcrypt')**
> 
> error fixed when using : **const bcrypt = require('bcryptjs')**

@Jclyoung I would suggest editing [your post above](https://github.com/TryGhost/node-sqlite3/issues/909#issuecomment-574823415) to remove this recommendation - you are recommending using [`bcryptjs`](https://www.npmjs.com/package/bcryptjs), an unmaintained library with the last publish in 2017.
