### ISSUE TITLE
Building for NWJS

### ISSUE THREAD

**Issue by alborq** [mapbox/node-sqlite3#692] opened 2016-08-19 14:52 UTC
Hello

Step 1) npm install nw-gyp -g DONE
Step 2) npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=ia32 --target=0.14.7 ERROR 
```
> sqlite3@3.1.4 install C:\web\root_dir\Borne\demo bbB\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build


C:\web\root_dir\Borne\demo bbB\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd configure --fallback-to-build --module=C:\web\root_dir\Borne\demo bbB\node_modules\sqlite3\lib\binding\node-webkit-v0.14.7-win32-ia32\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\web\root_dir\Borne\demo bbB\node_modules\sqlite3\lib\binding\node-webkit-v0.14.7-win32-ia32' (Error: spawn nw-gyp.cmd ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\web\root_dir\Borne\demo bbB\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:77:29)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:344:16)
node-pre-gyp ERR! stack     at nextTickCallbackWith2Args (node.js:442:9)
node-pre-gyp ERR! stack     at process._tickCallback (node.js:356:17)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\web\\root_dir\\Borne\\demo bbB\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\web\root_dir\Borne\demo bbB\node_modules\sqlite3
node-pre-gyp ERR! node -v v4.4.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp.cmd configure --fallback-to-build --module=C:\web\root_dir\Borne\demo bbB\node_modules\sqlite3\lib\binding\node-webkit-v0.14.7-win32-ia32\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\web\root_dir\Borne\demo bbB\node_modules\sqlite3\lib\binding\node-webkit-v0.14.7-win32-ia32' (Error: spawn nw-gyp.cmd ENOENT)
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3" "--build-from-source" "--runtime=node-webkit" "--target_arch=ia32" "--target=0.14.7"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\web\root_dir\Borne\demo bbB\npm-debug.log
```
npm-debug: http://pastebin.com/Q8azMLqv 

How Solve ? what is a problem ? 
Related to : #481

**Comment by tmcw** [comment] 2016-09-06 22:31
Duplicate of https://github.com/mapbox/node-sqlite3/issues/497

**Closed by tmcw** 2016-09-06 22:31 UTC
