### ISSUE TITLE
yarn add sqlite3 package failed to install

### ISSUE THREAD

**Issue by Solrac23** [mapbox/node-sqlite3#1430] opened 2021-01-20 04:40 UTC
OS: Pop_OS 64bits
npm: 6.14.8
node: 12.19.0
yarn: 1.22.5

message error:

`npm install sqlite3   
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> sqlite3@5.0.1 install /media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@12.19.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/sqlite3/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c
/bin/sh: 1: Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/sqlite3/build/Release/lib.host:/media/carlossantos/Arquivos/Carlos: not found
/bin/sh: 1: python: not found
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c] Error 127
make: Leaving directory '/media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.8.0-7630-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/sqlite3/lib/binding/napi-v6-linux-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd /media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/sqlite3
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/sqlite3/lib/binding/napi-v6-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 5.8.0-7630-generic
node-pre-gyp ERR! command "/usr/bin/node" "/media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/sqlite3
node-pre-gyp ERR! node -v v12.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/media/carlossantos/Arquivos/Carlos Eduardo/Documents/Cursos/Omnstack11/aulas/backend/node_modules/sqlite3/lib/binding/napi-v6-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm WARN backend@1.0.0 No description
npm WARN backend@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@5.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@5.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/carlossantos/.npm/_logs/2021-01-20T04_33_14_736Z-debug.log`

**Comment by KpjComp** [comment] 2021-01-20 09:38
Just use 5.0.0, or install python-is-python3 so the build will work.

RANT_BEGIN
The whole point of semvar versioning is that a patch releases should never break an update.  Unfortunately due to the nature of binary builds this is not really the case.  5.0.1 was released over 4 months ago, so why there is no binary builds for this, I'm not sure.  The problem is even worse for Windows users, getting a build chain running is sometimes a right pain, and Linux or Windows expecting end users to have the build chains in place is not ideal.  Sorry for the rant, but it's things like this that really spoil the node/npm ecosystem.
RANT_END

**Comment by maxwellsmart84** [comment] 2021-01-20 15:45
I have the same issue - downgrading to 5.0

**Comment by maxwellsmart84** [comment] 2021-01-20 15:56
Coming back to confirm that downgrading to 5.0.0 fixed the issue kudos @KpjComp

**Comment by Solrac23** [comment] 2021-01-20 19:53
OK, @KpjComp  i'll try to install version 5.0

**Comment by Solrac23** [comment] 2021-01-20 20:00
It's really only working with version 5.0.0. But thank you very much.

**Comment by maxwellsmart84** [comment] 2021-01-21 16:38
@Solrac23  are we sure we want to close this issue? I dont think a minor semver should have any breaking change.  Root cause still hasn't been found.

**Comment by Solrac23** [comment] 2021-01-21 18:36
@maxwellsmart84 you're right, i will leave the issue open so that maybe they can find some solution.

But for hour version 5.0.0 has already helped me a lot.

**Comment by zoosm3** [comment] 2021-01-25 08:32
```
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@10.23.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
```

Installation has failed because the tars are not found. Any ways to fix them?

**Comment by ariffb25** [comment] 2021-01-26 05:33
> ```
> node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
> node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
> node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@10.23.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
> node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
> ```
> 
> Installation has failed because the tars are not found. Any ways to fix them?

install manually npm install https://github.com/mapbox/node-sqlite3/tarball/master

**Comment by iwillreku3206** [comment] 2021-02-22 12:52
Can confirm install fails with yarn (using command `yarn add sqlite3` to install) on Windows 10. Installing an older version `5.0.0` using `yarn add sqlite3@5.0.0` works for me

**Comment by kewde** [comment] 2021-03-08 14:38
Please update to the latest version, I have attempted to resolve the issues with 5.0.0 but it will take longer than expected.

**Closed by kewde** 2021-03-08 14:38 UTC
