### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by bennyn** [mapbox/node-sqlite3#892] opened 2017-09-27 07:14 UTC
Everytime I run `npm version patch` in [my application](https://github.com/welovecoding/website), I am hitting the following error:

## Error log

> npm ERR! path D:\dev\projects\welovecoding\website\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\are-we-there-yet\node_modules\delegates
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\dev\projects\welovecoding\website\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\are-we-there-yet\node_modules\delegates' -> 'D:\dev\projects\welovecoding\website\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\are-we-there-yet\node_modules\.delegates.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bennyn\AppData\Roaming\npm-cache\_logs\2017-09-26T17_07_33_589Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4294963238
npm ERR! @welovecoding/website@1.0.18 preversion: `npm install && npm run dist && npm test`
npm ERR! Exit status 4294963238
npm ERR!
npm ERR! Failed at the @welovecoding/website@1.0.18 preversion script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## System

**sqlite3:** 3.1.12
**Node.js:** 8.5.0
**npm:** 5.3.0
**OS:** Windows 10 Enterprise Edition

## Workaround

The error happens when using sqlite3 v3.1.12. A downgrade to sqlite3 v3.1.10 fixed the issue.

**Failing build:** https://travis-ci.org/welovecoding/website/builds/280064166#L2132-L2143
**Downgraded build:** https://travis-ci.org/welovecoding/website/builds/280195215#L2146-L2152

Successful build log (sqlite v3.1.10):

> > sqlite3@3.1.10 install /tmp/build_acfb920907bdd09025c19557488aa38f/node_modules/sqlite3
       > node-pre-gyp install --fallback-to-build
       [sqlite3] Success: "/tmp/build_acfb920907bdd09025c19557488aa38f/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node" is installed via remote

## Configuration

My `npm version` script looks as follows:

```json
"preversion": "npm install && npm run dist && npm test",
"version": "npm run dist",
"postversion": "git push && git push --tags",
```

**Comment by Ionaru** [comment] 2017-09-27 08:12
Duplicate of #890

**Comment by springmeyer** [comment] 2017-10-13 01:07
#890 is solved

**Closed by springmeyer** 2017-10-13 01:07 UTC
